version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /packages/ui
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ui-root

  - package-ecosystem: npm
    directory: /ui/react
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ui-react

  - package-ecosystem: npm
    directory: /ui/vanilla
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ui-vanilla

  - package-ecosystem: npm
    directory: /ui/vue
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ui-vue

  - package-ecosystem: npm
    directory: /ui/svelte
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ui-svelte

  - package-ecosystem: npm
    directory: /ui/angular
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ui-angular

  - package-ecosystem: npm
    directory: /ui/lit
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ui-lit

  - package-ecosystem: npm
    directory: /ui/solid
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ui-solid

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
