import { UIElement } from '../core/UIElement'; import { register } from '../core/register';
export interface UICommand { id:string; label:string; group?:string; shortcut?:string; description?:string; disabled?:boolean; }
export class UICommandPalette extends UIElement {
  static observedAttributes=['open','placeholder','label']; private _commands:UICommand[]=[]; private query='';
  set commands(value:UICommand[]){this._commands=value??[];this.render();} get commands():UICommand[]{return this._commands;}
  protected styles():string{return `:host{display:none;position:fixed;inset:0;z-index:120;background:rgb(2 6 23/.58);padding:12vh 1rem 1rem}:host([open]){display:grid;align-items:start;justify-items:center}.panel{width:min(40rem,100%);background:var(--ui-color-surface);border:1px solid var(--ui-color-border,#cbd5e1);border-radius:.75rem;box-shadow:0 24px 60px rgb(0 0 0/.35);overflow:hidden}.search{display:flex;align-items:center;border-bottom:1px solid var(--ui-color-border,#cbd5e1)}input{flex:1;padding:.9rem 1rem;border:0;outline:0;background:transparent;color:var(--ui-color-text);font:inherit}.list{max-height:22rem;overflow:auto;padding:.4rem}.item{display:grid;grid-template-columns:1fr auto;gap:.2rem .75rem;padding:.65rem .75rem;border-radius:.4rem;cursor:pointer}.item:hover,.item:focus{outline:0;background:color-mix(in srgb,var(--ui-color-primary,#4f46e5) 12%,transparent)}.item small{color:var(--ui-color-text-secondary,#64748b)}kbd{grid-row:1/3;grid-column:2;align-self:center;padding:.1rem .35rem;border:1px solid var(--ui-color-border,#cbd5e1);border-radius:.25rem;font-size:.7rem}`;}
  protected template():string{const filtered=this.commands.filter(c=>`${c.label} ${c.group??''} ${c.description??''}`.toLowerCase().includes(this.query.toLowerCase()));return `<div class="panel" role="dialog" aria-label="${this.getAttr('label','Command palette')}"><div class="search"><input autofocus placeholder="${this.getAttr('placeholder','Type a command')}" value="${this.query}" aria-label="Search commands"/></div><div class="list" role="listbox">${filtered.map(c=>`<div class="item" role="option" tabindex="0" data-id="${c.id}" aria-disabled="${Boolean(c.disabled)}"><strong>${c.label}</strong><small>${c.description??c.group??''}</small>${c.shortcut?`<kbd>${c.shortcut}</kbd>`:''}</div>`).join('')||'<div class="item">No matching commands</div>'}</div></div>`;}
  protected onRendered():void{const input=this.$<HTMLInputElement>('input');input?.addEventListener('input',()=>{this.query=input.value;this.render();this.$<HTMLInputElement>('input')?.focus();});input?.addEventListener('keydown',e=>{if(e.key==='Escape')this.removeAttribute('open');});this.$$<HTMLElement>('[data-id]').forEach(item=>{const run=()=>{if(item.getAttribute('aria-disabled')==='true')return;this.emit('ui-command',{id:item.dataset.id});this.removeAttribute('open');};item.addEventListener('click',run);item.addEventListener('keydown',e=>{if((e as KeyboardEvent).key==='Enter')run();});});}
}
register('ui-command-palette',UICommandPalette);
