import { UIElement } from '../core/UIElement';
import { register } from '../core/register';

export interface AdvancedGridColumn { field:string; headerName:string; width?:number; minWidth?:number; maxWidth?:number; align?:'left'|'center'|'right'; sortable?:boolean; filterable?:boolean; editable?:boolean; hidden?:boolean; pinned?:'left'|'right'; }
export interface GridFilter { field:string; operator:'contains'|'equals'|'startsWith'|'endsWith'|'gt'|'gte'|'lt'|'lte'; value:string|number; }
export interface GridSort { field:string; direction:'asc'|'desc'; }
export interface GridViewState { columns:Array<Pick<AdvancedGridColumn,'field'|'width'|'hidden'|'pinned'>>; sort:GridSort[]; filters:GridFilter[]; search:string; }

export class UIDataGridAdvanced extends UIElement {
  static observedAttributes=['checkbox-selection','editable','column-reorder','column-resize','virtualized','height','row-height','toolbar','exportable','page-size'];
  private _columns:AdvancedGridColumn[]=[]; private _rows:Record<string,unknown>[]=[]; private _filters:GridFilter[]=[]; private _sort:GridSort[]=[]; private selected=new Set<string>(); private search=''; private page=0; private scrollOffset=0; private dragged='';
  set columns(value:AdvancedGridColumn[]){this._columns=structuredClone(value??[]);this.render();} get columns(){return this._columns;}
  set rows(value:Record<string,unknown>[]){this._rows=value??[];this.page=0;this.render();} get rows(){return this._rows;}
  set filters(value:GridFilter[]){this._filters=value??[];this.page=0;this.render();} get filters(){return this._filters;}
  set sortModel(value:GridSort[]){this._sort=value??[];this.render();} get sortModel(){return this._sort;}
  get selectedRowIds():readonly string[]{return [...this.selected];}
  getViewState():GridViewState{return{columns:this.columns.map(({field,width,hidden,pinned})=>({field,width,hidden,pinned})),sort:structuredClone(this._sort),filters:structuredClone(this._filters),search:this.search};}
  applyViewState(state:GridViewState):void{const map=new Map(state.columns.map(column=>[column.field,column]));this._columns=this._columns.map(column=>({...column,...map.get(column.field)}));this._sort=structuredClone(state.sort);this._filters=structuredClone(state.filters);this.search=state.search;this.render();this.emit('ui-view-change',this.getViewState());}
  exportCSV():string{const cols=this.visibleColumns(),quote=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;return[cols.map(col=>quote(col.headerName)).join(','),...this.processRows().map(row=>cols.map(col=>quote(row[col.field])).join(','))].join('\n');}
  protected styles():string{return`:host{display:block;min-width:0}.shell{display:grid;grid-template-rows:auto minmax(0,1fr) auto;height:var(--height,auto);border:1px solid var(--ui-color-border,#cbd5e1);border-radius:.6rem;overflow:hidden;background:var(--ui-color-surface)}.toolbar,.pager{display:flex;align-items:center;gap:.5rem;padding:.45rem .55rem;border-bottom:1px solid var(--ui-color-border,#cbd5e1)}.pager{justify-content:flex-end;border-top:1px solid var(--ui-color-border,#cbd5e1);border-bottom:0}.toolbar input{flex:1;min-width:8rem;padding:.45rem .55rem;border:1px solid var(--ui-color-border);border-radius:.35rem;background:transparent;color:var(--ui-color-text)}button{padding:.38rem .55rem;border:1px solid var(--ui-color-border);border-radius:.35rem;background:transparent;color:var(--ui-color-text);cursor:pointer}.viewport{overflow:auto;min-height:0}table{width:100%;border-collapse:separate;border-spacing:0;table-layout:fixed;font-size:.82rem}th,td{height:var(--row,38px);padding:0 .6rem;border-right:1px solid var(--ui-color-border);border-bottom:1px solid var(--ui-color-border);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}th{position:sticky;top:0;z-index:3;background:var(--ui-color-surface-variant,#0f172a);color:var(--ui-color-text-secondary);text-align:left;user-select:none}.sortable{cursor:pointer}.header{position:relative;display:flex;align-items:center;gap:.3rem;height:100%}.resize{position:absolute;inset:0 -3px 0 auto;width:7px;cursor:col-resize}.pinned{position:sticky;left:var(--left,0);z-index:2;background:var(--ui-color-surface)}th.pinned{z-index:5;background:var(--ui-color-surface-variant,#0f172a)}tr:hover td{background:color-mix(in srgb,var(--ui-color-primary) 6%,var(--ui-color-surface))}tr.selected td{background:color-mix(in srgb,var(--ui-color-primary) 14%,var(--ui-color-surface))}.empty{text-align:center;padding:2rem;color:var(--ui-color-text-secondary)}.spacer td{padding:0;border:0}.edit{width:100%;height:calc(var(--row) - 6px);border:1px solid var(--ui-color-primary);background:var(--ui-color-surface);color:var(--ui-color-text)}`;}
  protected template():string{
    const cols=this.visibleColumns(),processed=this.processRows(),rowHeight=this.getNumAttr('row-height',38),pageSize=this.getNumAttr('page-size',0),pages=pageSize?Math.max(1,Math.ceil(processed.length/pageSize)):1;let start=pageSize?this.page*pageSize:0,end=pageSize?Math.min(processed.length,start+pageSize):processed.length,top=0,bottom=0;
    if(this.getBoolAttr('virtualized')&&!pageSize){const height=this.getNumAttr('height',420);start=Math.max(0,Math.floor(this.scrollOffset/rowHeight)-4);end=Math.min(processed.length,start+Math.ceil(height/rowHeight)+8);top=start*rowHeight;bottom=(processed.length-end)*rowHeight;}
    const checkbox=this.getBoolAttr('checkbox-selection'),offsets=new Map<string,number>();let left=checkbox?38:0;for(const col of cols)if(col.pinned==='left'){offsets.set(col.field,left);left+=col.width??140;}
    const head=`${checkbox?'<th style="width:38px" class="pinned"><input class="all" type="checkbox" aria-label="Select visible rows"/></th>':''}${cols.map(col=>{const sorted=this._sort.find(item=>item.field===col.field),pinned=col.pinned==='left'?` pinned" style="--left:${offsets.get(col.field)}px;width:${col.width??140}px`:`" style="width:${col.width??140}px`;return`<th data-field="${col.field}" draggable="${this.getBoolAttr('column-reorder')}" class="${col.sortable===false?'':'sortable'}${pinned}"><span class="header">${col.headerName}${sorted?(sorted.direction==='asc'?' ▲':' ▼'):''}${this.getBoolAttr('column-resize')?'<span class="resize"></span>':''}</span></th>`;}).join('')}`;
    const rows=processed.slice(start,end).map((row,relative)=>{const index=start+relative,id=this.rowId(row,index);return`<tr data-id="${id}" data-index="${index}" class="${this.selected.has(id)?'selected':''}">${checkbox?`<td class="pinned" style="--left:0"><input class="select" type="checkbox" ${this.selected.has(id)?'checked':''}/></td>`:''}${cols.map(col=>`<td data-field="${col.field}" class="${col.pinned==='left'?'pinned':''}" style="--left:${offsets.get(col.field)??0}px;text-align:${col.align??'left'}">${String(row[col.field]??'')}</td>`).join('')}</tr>`;}).join('');
    const toolbar=this.getBoolAttr('toolbar')?`<div class="toolbar"><input class="search" type="search" aria-label="Search rows" placeholder="Search all columns" value="${this.search}"/><span>${processed.length.toLocaleString()} rows</span>${this.getBoolAttr('exportable')?'<button data-action="export">Export CSV</button>':''}</div>`:'';
    const pager=pageSize?`<div class="pager"><span>${processed.length?`${start+1}–${end}`:0} of ${processed.length}</span><button data-action="prev" ${this.page===0?'disabled':''}>Previous</button><span>${this.page+1} / ${pages}</span><button data-action="next" ${this.page>=pages-1?'disabled':''}>Next</button></div>`:'';
    return`<div class="shell" style="--height:${this.hasAttribute('height')?`${this.getNumAttr('height')}px`:'auto'};--row:${rowHeight}px">${toolbar}<div class="viewport"><table role="grid"><thead><tr>${head}</tr></thead><tbody>${top?`<tr class="spacer"><td colspan="${cols.length+(checkbox?1:0)}" style="height:${top}px"></td></tr>`:''}${rows||`<tr><td class="empty" colspan="${cols.length+(checkbox?1:0)}">No matching rows</td></tr>`}${bottom?`<tr class="spacer"><td colspan="${cols.length+(checkbox?1:0)}" style="height:${bottom}px"></td></tr>`:''}</tbody></table></div>${pager}</div>`;
  }
  protected onRendered():void{
    const viewport=this.$<HTMLElement>('.viewport');if(viewport)viewport.scrollTop=this.scrollOffset;viewport?.addEventListener('scroll',()=>{if(this.getBoolAttr('virtualized')){this.scrollOffset=viewport.scrollTop;this.render();}});
    this.$<HTMLInputElement>('.search')?.addEventListener('input',event=>{this.search=(event.currentTarget as HTMLInputElement).value;this.page=0;this.render();this.emit('ui-filter',{search:this.search,filters:this._filters});});
    this.$$<HTMLTableCellElement>('th[data-field]').forEach(header=>{header.addEventListener('click',event=>{if((event.target as HTMLElement).classList.contains('resize'))return;const column=this._columns.find(item=>item.field===header.dataset.field);if(column?.sortable===false)return;const existing=this._sort.find(item=>item.field===header.dataset.field),next={field:header.dataset.field!,direction:(existing?.direction==='asc'?'desc':'asc') as 'asc'|'desc'};this._sort=(event.shiftKey?this._sort.filter(item=>item.field!==next.field):[]).concat(next);this.render();this.emit('ui-sort',{sort:this._sort});});header.addEventListener('dragstart',()=>{this.dragged=header.dataset.field??'';});header.addEventListener('dragover',event=>event.preventDefault());header.addEventListener('drop',()=>this.reorder(this.dragged,header.dataset.field??''));this.bindResize(header);});
    this.$$<HTMLTableRowElement>('tr[data-id]').forEach(rowElement=>{rowElement.querySelector<HTMLInputElement>('.select')?.addEventListener('change',event=>{const checked=(event.currentTarget as HTMLInputElement).checked,id=rowElement.dataset.id!;if(checked)this.selected.add(id);else this.selected.delete(id);this.render();this.emit('ui-selection',{rowIds:[...this.selected]});});rowElement.addEventListener('click',event=>{if(!(event.target as HTMLElement).matches('input'))this.emit('ui-row-click',{rowId:rowElement.dataset.id,row:this.processRows()[Number(rowElement.dataset.index)]});});if(this.getBoolAttr('editable'))rowElement.querySelectorAll<HTMLTableCellElement>('td[data-field]').forEach(cell=>cell.addEventListener('dblclick',()=>this.beginEdit(cell,Number(rowElement.dataset.index))));});
    this.$<HTMLInputElement>('.all')?.addEventListener('change',event=>{const checked=(event.currentTarget as HTMLInputElement).checked;for(const row of this.$$<HTMLTableRowElement>('tr[data-id]')){if(checked)this.selected.add(row.dataset.id!);else this.selected.delete(row.dataset.id!);}this.render();this.emit('ui-selection',{rowIds:[...this.selected]});});
    this.$('[data-action=prev]')?.addEventListener('click',()=>{this.page=Math.max(0,this.page-1);this.render();});this.$('[data-action=next]')?.addEventListener('click',()=>{this.page+=1;this.render();});this.$('[data-action=export]')?.addEventListener('click',()=>this.emit('ui-export',{format:'csv',content:this.exportCSV()}));
  }
  private visibleColumns(){return this._columns.filter(column=>!column.hidden);} private rowId(row:Record<string,unknown>,index:number){return String(row['id']??row['key']??index);}
  private processRows(){const query=this.search.trim().toLowerCase();let rows=this._rows.filter(row=>(!query||this.visibleColumns().some(col=>String(row[col.field]??'').toLowerCase().includes(query)))&&this._filters.every(filter=>this.matchesFilter(row[filter.field],filter)));if(this._sort.length)rows=[...rows].sort((a,b)=>{for(const sort of this._sort){const left=a[sort.field],right=b[sort.field],result=typeof left==='number'&&typeof right==='number'?left-right:String(left??'').localeCompare(String(right??''),undefined,{numeric:true});if(result)return sort.direction==='asc'?result:-result;}return 0;});return rows;}
  private matchesFilter(value:unknown,filter:GridFilter){const actual=String(value??'').toLowerCase(),target=String(filter.value).toLowerCase();switch(filter.operator){case'equals':return actual===target;case'startsWith':return actual.startsWith(target);case'endsWith':return actual.endsWith(target);case'gt':return Number(value)>Number(filter.value);case'gte':return Number(value)>=Number(filter.value);case'lt':return Number(value)<Number(filter.value);case'lte':return Number(value)<=Number(filter.value);default:return actual.includes(target);}}
  private reorder(fromField:string,toField:string){const from=this._columns.findIndex(item=>item.field===fromField),to=this._columns.findIndex(item=>item.field===toField);if(from<0||to<0||from===to)return;const[column]=this._columns.splice(from,1);if(column)this._columns.splice(to,0,column);this.render();this.emit('ui-column-order',{fields:this._columns.map(item=>item.field)});}
  private bindResize(header:HTMLTableCellElement){const handle=header.querySelector<HTMLElement>('.resize'),column=this._columns.find(item=>item.field===header.dataset.field);if(!handle||!column)return;handle.addEventListener('pointerdown',event=>{event.stopPropagation();const start=event.clientX,width=column.width??140;handle.setPointerCapture(event.pointerId);const move=(next:PointerEvent)=>{column.width=Math.min(column.maxWidth??600,Math.max(column.minWidth??70,width+next.clientX-start));this.render();};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',()=>{handle.removeEventListener('pointermove',move);this.emit('ui-column-resize',{field:column.field,width:column.width});},{once:true});});}
  private beginEdit(cell:HTMLTableCellElement,rowIndex:number){const field=cell.dataset.field!,column=this._columns.find(item=>item.field===field),row=this.processRows()[rowIndex];if(!column?.editable||!row)return;const previous=row[field];cell.innerHTML=`<input class="edit" value="${String(previous??'').replaceAll('"','&quot;')}"/>`;const input=cell.querySelector<HTMLInputElement>('input')!;input.focus();input.select();input.addEventListener('blur',()=>{row[field]=input.value;this.render();this.emit('ui-cell-edit',{rowId:this.rowId(row,rowIndex),field,value:input.value,previousValue:previous,row});},{once:true});input.addEventListener('keydown',event=>{if(event.key==='Enter')input.blur();if(event.key==='Escape')this.render();});}
}
register('ui-data-grid-advanced',UIDataGridAdvanced);
