import { UIElement } from '../core/UIElement'; import { register } from '../core/register';
export class UITagInput extends UIElement {
  static observedAttributes=['label','placeholder','disabled','max-tags','allow-duplicates']; private _tags:string[]=[];
  set tags(value:string[]){this._tags=Array.isArray(value)?value:[];this.render();} get tags():string[]{return this._tags;}
  protected styles():string{return `:host{display:grid;gap:.35rem}label{font-size:.875rem;font-weight:600}.control{display:flex;align-items:center;flex-wrap:wrap;gap:.35rem;min-height:2.6rem;padding:.35rem;border:1px solid var(--ui-color-border,#cbd5e1);border-radius:.5rem;background:var(--ui-color-surface)}.tag{display:inline-flex;align-items:center;gap:.25rem;padding:.2rem .45rem;border-radius:999px;background:color-mix(in srgb,var(--ui-color-primary,#4f46e5) 14%,transparent);font-size:.8rem}.tag button{all:unset;cursor:pointer}input{flex:1;min-width:8rem;padding:.25rem;border:0;outline:0;background:transparent;color:var(--ui-color-text);font:inherit}`;}
  protected template():string{return `<label>${this.getAttr('label')}</label><div class="control">${this.tags.map((tag,index)=>`<span class="tag">${tag}<button type="button" data-index="${index}" aria-label="Remove ${tag}">×</button></span>`).join('')}<input placeholder="${this.getAttr('placeholder')}" ${this.getBoolAttr('disabled')?'disabled':''}/></div>`;}
  protected onRendered():void{const input=this.$<HTMLInputElement>('input');input?.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===',')&&input.value.trim()){event.preventDefault();this.addTag(input.value.trim());}if(event.key==='Backspace'&&!input.value&&this.tags.length)this.removeTag(this.tags.length-1);});this.$$<HTMLButtonElement>('[data-index]').forEach(button=>button.addEventListener('click',()=>this.removeTag(Number(button.dataset.index))));}
  private addTag(tag:string):void{if(this.tags.length>=this.getNumAttr('max-tags',Infinity))return;if(!this.getBoolAttr('allow-duplicates')&&this.tags.includes(tag))return;this._tags=[...this.tags,tag];this.render();this.emit('ui-change',{tags:this.tags});} private removeTag(index:number):void{this._tags=this.tags.filter((_,itemIndex)=>itemIndex!==index);this.render();this.emit('ui-change',{tags:this.tags});}
}
register('ui-tag-input',UITagInput);
