/**
 * @risklab/ui-react
 * Full-featured React component library with StyleX/xstyle compatibility.
 * A comprehensive replacement for MUI with no external runtime dependencies.
 */

// --- Theme ----------------------------------------------------
export {
  lightTheme,
  darkTheme,
  ThemeProvider,
  ThemeContext,
  useTheme,
} from './theme';
export type {
  UITheme,
  ThemeMode,
  ThemeTokens,
  ColorScale,
  ThemeProviderProps,
} from './theme';

// --- Styling utilities ----------------------------------------
export { cx, sx, xstyle } from './styling';
export type { XStyleProp, SizeVariant, ColorVariant, BaseProps } from './styling';

// --- Layout -------------------------------------------------------------------
export {
  Box,
  Container,
  Grid,
  GridItem,
  Stack,
  Flex,
  Divider,
  Spacer,
  AspectRatio,
  Center,
  ScrollArea,
  Masonry,
  SplitPane,
} from './layout';
export type {
  BoxProps,
  BoxOwnProps,
  ContainerProps,
  MaxWidthPreset,
  GridProps,
  GridItemProps,
  StackProps,
  FlexProps,
  DividerProps,
  SpacerProps,
  AspectRatioProps,
  CenterProps,
  ScrollAreaProps,
  MasonryProps,
  SplitPaneProps,
  ResizableDirection,
} from './layout';

// --- Inputs ---------------------------------------------------
export {
  Button,
  IconButton,
  ButtonGroup,
  ButtonGroupContext,
  useButtonGroup,
  TextField,
  Select,
  Checkbox,
  Radio,
  RadioGroup,
  Switch,
  Slider,
  ToggleButton,
  ToggleButtonGroup,
  Autocomplete,
  Rating,
  NumberInput,
  OTPInput,
  TagInput,
  SpeedDial,
  DropZone,
  FormControl,
  FormLabel,
  FormHelperText,
  FormErrorMessage,
  useFormControl,
} from './inputs';
export type {
  ButtonProps,
  ButtonVariant,
  IconButtonProps,
  IconButtonVariant,
  ButtonGroupProps,
  ButtonGroupContextValue,
  TextFieldProps,
  TextFieldVariant,
  SelectProps,
  SelectOption,
  SelectVariant,
  CheckboxProps,
  RadioProps,
  RadioGroupProps,
  SwitchProps,
  SliderProps,
  SliderMark,
  ToggleButtonProps,
  ToggleButtonGroupProps,
  AutocompleteProps,
  AutocompleteOption,
  RatingProps,
  NumberInputProps,
  OTPInputProps,
  TagInputProps,
  SpeedDialProps,
  SpeedDialAction,
  DropZoneProps,
  DropZoneFile,
  FormControlProps,
  FormLabelProps,
  FormHelperTextProps,
  FormErrorMessageProps,
} from './inputs';

// --- Data Display ---------------------------------------------
export {
  Typography,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableCell,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  ListItemAction,
  ListSubheader,
  Chip,
  Badge,
  Avatar,
  AvatarGroup,
  Tooltip,
  Card,
  CardHeader,
  CardMedia,
  CardContent,
  CardActions,
  DataGrid,
  Timeline,
  TimelineContent,
  TimelineDot,
  TimelineConnector,
  TreeView,
  ImageList,
  Callout,
  EmptyState,
} from './data-display';
export type {
  TypographyProps,
  TypographyVariant,
  TypographyWeight,
  TypographyAlign,
  TableProps,
  TableSize,
  TableSortDirection,
  Column,
  TableHeadProps,
  TableBodyProps,
  TableRowProps,
  TableCellProps,
  ListProps,
  ListVariant,
  ListItemProps,
  ListItemIconProps,
  ListItemTextProps,
  ListItemActionProps,
  ListSubheaderProps,
  ChipProps,
  ChipVariant,
  BadgeProps,
  BadgeVariant,
  BadgeOverlap,
  BadgeAnchorOrigin,
  AvatarProps,
  AvatarVariant,
  AvatarGroupProps,
  TooltipProps,
  TooltipPlacement,
  TooltipVariant,
  CardProps,
  CardVariant,
  CardHeaderProps,
  CardMediaProps,
  CardContentProps,
  CardActionsProps,
  DataGridProps,
  DataGridColumn,
  SortModelEntry,
  FilterModelEntry,
  TimelineProps,
  TimelineItemData,
  TreeViewProps,
  TreeItemData,
  ImageListProps,
  ImageListItemData,
  CalloutProps,
  CalloutVariant,
  EmptyStateProps,
} from './data-display';

// --- Feedback -------------------------------------------------
export {
  Alert,
  Toast,
  ToastProvider,
  useToast,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  LinearProgress,
  CircularProgress,
  Skeleton,
  Backdrop,
  Snackbar,
} from './feedback';
export type {
  AlertProps,
  ToastProps,
  ToastProviderProps,
  ToastOptions,
  DialogProps,
  DialogTitleProps,
  DialogContentProps,
  DialogActionsProps,
  LinearProgressProps,
  CircularProgressProps,
  SkeletonProps,
  BackdropProps,
  SnackbarProps,
  AnchorOrigin,
} from './feedback';

// --- Navigation -----------------------------------------------
export {
  Tabs,
  TabList,
  Tab,
  TabPanel,
  Breadcrumbs,
  Drawer,
  AppBar,
  Toolbar,
  NavItem,
  Menu,
  MenuItem,
  Pagination,
  Link,
  Stepper,
  CommandPalette,
  ContextMenu,
} from './navigation';
export type {
  TabsProps,
  TabListProps,
  TabProps,
  TabPanelProps,
  BreadcrumbsProps,
  BreadcrumbItem,
  DrawerProps,
  AppBarProps,
  ToolbarProps,
  NavItemProps,
  MenuProps,
  MenuItemProps,
  MenuItemData,
  PaginationProps,
  LinkProps,
  StepperProps,
  StepperStep,
  CommandPaletteProps,
  CommandItem,
  CommandGroup,
  ContextMenuProps,
  ContextMenuItem,
} from './navigation';

// --- Surfaces -------------------------------------------------
export {
  Paper,
  Accordion,
  AccordionSummary,
  AccordionDetails,
} from './surfaces';
export type {
  PaperProps,
  PaperVariant,
  AccordionProps,
  AccordionItem,
  AccordionSummaryProps,
  AccordionDetailsProps,
} from './surfaces';

// --- Utils ----------------------------------------------------
export {
  useMediaQuery,
  useBreakpoint,
  useMergedRef,
  useClickAway,
  useFocusTrap,
  Transition,
  Fade,
  Slide,
  Collapse,
  Portal,
  VirtualList,
} from './utils';
export type {
  Breakpoint,
  TransitionProps,
  FadeProps,
  SlideProps,
  CollapseProps,
  TransitionState,
  PortalProps,
  VirtualListProps,
} from './utils';
